### ISSUE TITLE
[ ping ] - Very helpful feature that surly many will want to implement.

### ISSUE THREAD

**Issue by good-faith** [bahmutov/cypress-gh-action-monorepo#1]
Could we get a mono-repo example with nrwl running multiple api servers and clients? I got continuous integration working with one api server and one client through Azure Pipelines but this would be a nice feature.

**Comment by bahmutov** [comment]
can you point me at a public repo with such setup?

**Comment by good-faith** [comment]
I have a working repo with one client and one server hosted on microsoft devops that uses the exact azure-pipelines yaml that is in the repo I'm working on now and all tests pass. 

I'm now working on implementing Auth-O, but what I would like is for affected files to run when a pull request is submitted. Is it possible to break out different clients and servers in the yaml so that when a pull request is made it evaluates the yaml and only runs the tests for the projects where there have been changes or additions made? 

An example for an admin app and a client app that consums the same api:

```
name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - run: yarn lint
      - name: Run clinet-e2e tests
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          # start server and wait for N seconds for it to respond before running tests.
          start: ng serve api
          wait-on: 'http://localhost:6000'
          wait-on-timeout: 40 # seconds
          # Cypress tests and config file are in "e2e" folder
          working-directory: admin-e2e
---
name: E2E
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - run: yarn lint
      - name: Run clinet-e2e tests
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          # start server and wait for N seconds for it to respond before running tests.
          start: ng serve api
          wait-on: 'http://localhost:6000'
          wait-on-timeout: 40 # seconds
          # Cypress tests and config file are in "e2e" folder
          working-directory: client-e2e

```

**Comment by bahmutov** [comment]
you can control if the workflow runs on changes for certain files only https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by good-faith** [comment]
The monorepo sytle may increase the complexity of how tests and deployments are performed with github actions. Haven't dedicated too much time to the area and was wondering if there was anyone working on this type of solution. From what I take from this, for the evaluation part - you are suggesting something like:

```
name: E2E
on: push
 paths:
  - 'admin/**'
  - 'api/**'
  - 'libs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - run: yarn lint
      - name: Run admin-e2e tests
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          # start server and wait for N seconds for it to respond before running tests.
          start: ng serve api
          wait-on: 'http://localhost:6000'
          wait-on-timeout: 40 # seconds
          # Cypress tests and config file are in "e2e" folder
          working-directory: admin-e2e
---
name: E2E
on: push
 paths:
  - 'client/**'
  - 'api/**'
  - 'libs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          # just perform install
          runTests: false
      - run: yarn lint
      - name: Run client-e2e tests
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          # start server and wait for N seconds for it to respond before running tests.
          start: ng serve api
          wait-on: 'http://localhost:6000'
          wait-on-timeout: 40 # seconds
          # Cypress tests and config file are in "e2e" folder
          working-directory: client-e2e
```

Thanks for the direction.
